package code.yousef.blog.theme

import com.varabyte.kobweb.compose.ui.graphics.Color

// Maroon
//enum class LightTheme(val color: Color) {
//    NAVBAR(color = Color.rgb(0xC32148)),
//    NAVBAR_LINK(color = Color.rgb(0x2F4F4F)),
//    BODY(color = Color.rgb(0xD3D3D3)),
//    LINK(color = Color.rgb(0x00008B)),
//    VISITED_LINK(color = Color.rgb(0x800080)),
//    BUTTON(color = Color.rgb(0xC32148)),
//    BUTTON_HOVER(color = Color.rgb(0xFF0000)),
//    BUTTON_FOCUS(color = Color.rgb(0x8B0000)),
//    BUTTON_PRESSED(color = Color.rgb(0x000000)),
//    TEXT(color = Color.rgb(0x000000)),
//    SWITCH_OFF(color = Color.rgb(0x808080)),
//    SWITCH_ON(color = Color.rgb(0x008000)),
//    SWITCH_KNOB(color = Color.rgb(0x000000)),
//    TAB(color = Color.rgb(0xC32148)),
//    TAB_BACKGROUND(color = Color.rgb(0xD3D3D3)),
//    TAB_SELECTED(color = Color.rgb(0xFF0000)),
//    TAB_HOVER(color = Color.rgb(0x2F4F4F)),
//    TAB_PRESSED(color = Color.rgb(0x000000)),
//    TAB_DISABLED(color = Color.rgb(0x808080)),
//    TAB_BORDER(color = Color.rgb(0x000000)),
//    TAB_SELECTED_BACKGROUND(color = Color.rgb(0xFF0000)),
//    TAB_SELECTED_BORDER(color = Color.rgb(0x000000)),
//}

// Oceanic
enum class LightTheme(val color: Color) {
    NAVBAR(color = Color.rgb(0x87CEEB)),
    NAVBAR_LINK(color = Color.rgb(0xe3f2fd)),
    BODY(color = Color.rgb(0xe3f2fd)),
    LINK(color = Color.rgb(0x87CEEB)),
    VISITED_LINK(color = Color.rgb(0x0000CD)),
    BUTTON(color = Color.rgb(0xAFEEEE)),
    BUTTON_HOVER(color = Color.rgb(0xAFEEEE)),
    BUTTON_FOCUS(color = Color.rgb(0x40E0D0)),
    BUTTON_PRESSED(color = Color.rgb(0x008080)),
    TEXT(color = Color.rgb(0x65737E)),
    SWITCH_OFF(color = Color.rgb(0xD3D3D3)),
    SWITCH_ON(color = Color.rgb(0xAFEEEE)),
    SWITCH_KNOB(color = Color.rgb(0x40E0D0)),
    TAB(color = Color.rgb(0x87CEEB)),
    TAB_BACKGROUND(color = Color.rgb(0xFFFFFF)),
    TAB_SELECTED(color = Color.rgb(0x00008B)),
    TAB_HOVER(color = Color.rgb(0xAFEEEE)),
    TAB_PRESSED(color = Color.rgb(0x008080)),
    TAB_DISABLED(color = Color.rgb(0xD3D3D3)),
    TAB_BORDER(color = Color.rgb(0x87CEEB)),
    TAB_SELECTED_BACKGROUND(color = Color.rgb(0x87CEEB)),
    TAB_SELECTED_BORDER(color = Color.rgb(0x00008B)),
    INPUT_FILLED(color = Color.rgb(0x65737E)),
    INPUT_FOCUSED_BORDER(color = Color.rgb(0xAFEEEE)),
    INPUT_HOVERED_BORDER(color = Color.rgb(0xAFEEEE)),
    INPUT_INVALID_BORDER(color = Color.rgb(0x008080)),
    INPUT_FILLED_HOVER(color = Color.rgb(0x40E0D0)),
    INPUT_FILLED_FOCUS(color = Color.rgb(0x65737E)),
    CHECKBOX_BACKGROUND(color = Color.rgb(0x65737E)),
}